module.exports = {
  reactStrictMode: true,
  env: {
    NEXT_APP_PINATA_API_KEY: process.env.NEXT_APP_PINATA_API_KEY,
    NEXT_APP_PINATA_API_SECRET: process.env.NEXT_APP_PINATA_API_SECRET,
    NEXT_APP_PINATA_GATEWAY: process.env.NEXT_APP_PINATA_GATEWAY,
    NEXT_APP_THETA_SA_ID: process.env.NEXT_APP_THETA_SA_ID,
    NEXT_APP_THETA_API_KEY: process.env.NEXT_APP_THETA_API_KEY,
    NEXT_PUBLIC_WLD_APP_ID: process.env.NEXT_PUBLIC_WLD_APP_ID,
    NEXT_PUBLIC_WLD_ACTION: process.env.NEXT_PUBLIC_WLD_ACTION,
  },
}
